### ISSUE TITLE
Make scrollable

### ISSUE THREAD

**Issue by dantaylorseo** [jobandtalent/CardStackController#12]
Is there any way to make the card view scrollable?

**Comment by victorBaro** [comment]
Not the whole card, but you can add a viewController with a scrollView inside.

**Comment by dantaylorseo** [comment]
How about tableViews? If I embed a table ViewController directly it doesn’t scroll?

**Comment by victorBaro** [comment]
Yes it does. As you see in this gif we used for the readme, the first controller embedded in the card is a tableview and it scrolls:
![](https://github.com/jobandtalent/CardStackController/raw/master/Assets/cards-app.gif?raw=true)

**Comment by dantaylorseo** [comment]
I got it working eventually with a table view inside a UIView just not a UITableViewController on its own. 

Sent from my mobile device. 

Dan Taylor
