### ISSUE TITLE
Transition snapshots

### ISSUE THREAD

**Issue by oscarbc96** [jobandtalent/CardStackController#5]
Hi,
This component is awesome. I was testing it and I get stuck trying to reload a collectionview in the original view with data added in stack view. I was debugging layers and I realize that screen snapshoots on transitions are not updated.

I was trying snapshotViewAfterScreenUpdates and all related methods but I couldn't solved it.
I'm newbie in iOS transitions, I don't know if that's correct. 

Original Screen:
<img width="401" alt="captura de pantalla 2017-02-06 a les 0 25 43" src="https://cloud.githubusercontent.com/assets/4248262/22630923/45224f8a-ec03-11e6-8f24-b884a2d8f832.png">
After add 1 player:
<img width="1099" alt="captura de pantalla 2017-02-06 a les 0 26 32" src="https://cloud.githubusercontent.com/assets/4248262/22630924/4525159e-ec03-11e6-90d2-00ec48e6f551.png">
After add 2 player:
<img width="1096" alt="captura de pantalla 2017-02-06 a les 0 28 29" src="https://cloud.githubusercontent.com/assets/4248262/22630925/4528c4b4-ec03-11e6-8a99-418527d7d13b.png">

Thanks in advance!

**Comment by victorBaro** [comment]
Hello @TGNA 
I am not sure what you are trying to achieve. This controller will present modally a ViewController. You don't need to use iOS Transitions API, the controller will automatically do it for you.

Can I see some code? It is tricky to answer your questions just by looking at some screenshots.
It looks to me that you are misusing the transitions API and stacking one screenshot on top of another (which you shouldn't). Try to delete all the snapshot related code and just present the viewController using the CardStackController.
I'd suggest you download the example project and take a look.

I am closing the issue as it is not related to the library. 

Let me know if you solve it!

**Comment by timglorioso** [comment]
@victorBaro I think this issue actually has merit... it seems the UIImageView snapshots don't get removed from the CardStackController's view upon dismissal. You can actually see this in @TGNA's view hierarchy screenshots (there's an extra snapshot view in the bottom one).

Digging into the code shows no sign of removing these snapshots. So I guess it's just a matter of figuring out the best place to do it, i.e. viewWillDisappear, dismissCard... 

Edit: I'm more than happy to get a PR going with some guidance 🙂
