### ISSUE TITLE
Unable to read license file

### ISSUE THREAD

**Issue by timglorioso** [jobandtalent/CardStackController#7]
Cocoapods complains:
`[!] Unable to read the license file ... /Pods/CardStackController/LICENSE for the spec CardStackController (0.1.0)`

Pretty sure it's because the filename has a .txt extension while the podspec specifies an extension-less file.

Because of this your awesome package isn't included in Cocoapods auto-generated acknowledgments file! :(

**Comment by victorBaro** [comment]
Thanks @timglorioso , good catch. I will update it asap.
